[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/api/*"
  to = "https://todolist-php-api.herokuapp.com/:splat"
  status = 200
  force = true